### ISSUE TITLE
Windows Defender deletes soulfu.exe on sight.

### ISSUE THREAD

**Issue by xmeadow** [szymor/soulfu#4]
Windows Defender description: https://www.microsoft.com/en-us/wdsi/threats/threat-search?query=Behavior:Win32/DefenseEvasion.A!ml

VirusTotal report: https://www.virustotal.com/gui/file/ff8d975b15dcd27db4ec4aca7df0715954695f60ab8ab3ccadc93fab88caf5bd

**Comment by szymor** [comment]
It seems to be a false alarm.

**Comment by szymor** [comment]
r2 release has the same issue. I guess it will repeat for the next releases built with Linux GCC. I will leave it open until anything changes.

**Comment by xmeadow** [comment]
My Windows Defender let it pass. I uploaded it also to onedrive, it did a "cloud-scan" but didn't delete the exe.
